export const SUGGESTIONS_REQUEST = 'SUGGESTIONS_REQUEST';
export const SUGGESTIONS_RESPONSE = 'SUGGESTIONS_RESPONSE';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_RESPONSE = 'SEARCH_RESPONSE';